spring:
  application:
    name: zibnote
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create-drop
  datasource:
    url: jdbc:h2:mem:tempDB;MODE=MySQL
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  expiration: 3600000

auth:
  front:
    redirect-uri: 
  kakao:
    client_id: 
    redirect_uri: 
  naver:
    client_id: 
    client_secret: 
    redirect_uri: 
    state: 
