spring:
  application:
    name: zibnote
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create
  datasource:
    url: jdbc:h2:mem:tempDB
    username: sa
    password: 
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
